export const TOGGLE_SIDE_NAV = 'TOGGLE_SIDE_NAV';
export const UPDATE_DIMENSIONS = 'UPDATE_DIMENSIONS';
export const FETCH_CHILDREN = 'FETCH_CHILDREN';
export const FETCH_COIN_DATA = 'FETCH_COIN_DATA';
